# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CMMS.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1033, 814)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 1013, 618))
        self.page.setObjectName("page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.page)
        self.tabWidget.setIconSize(QtCore.QSize(100, 50))
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.splitter_2 = QtWidgets.QSplitter(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.label_29 = QtWidgets.QLabel(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setObjectName("label_29")
        self.DashTasksCount_label = QtWidgets.QLabel(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DashTasksCount_label.sizePolicy().hasHeightForWidth())
        self.DashTasksCount_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.DashTasksCount_label.setFont(font)
        self.DashTasksCount_label.setObjectName("DashTasksCount_label")
        self.gridLayout_10.addWidget(self.splitter_2, 1, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_3.addWidget(self.lineEdit)
        self.gridLayout_10.addWidget(self.groupBox_3, 0, 0, 1, 5)
        self.splitter_5 = QtWidgets.QSplitter(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_5.sizePolicy().hasHeightForWidth())
        self.splitter_5.setSizePolicy(sizePolicy)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.label_35 = QtWidgets.QLabel(self.splitter_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_35.sizePolicy().hasHeightForWidth())
        self.label_35.setSizePolicy(sizePolicy)
        self.label_35.setObjectName("label_35")
        self.DashDepatmentsCount_label = QtWidgets.QLabel(self.splitter_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DashDepatmentsCount_label.sizePolicy().hasHeightForWidth())
        self.DashDepatmentsCount_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.DashDepatmentsCount_label.setFont(font)
        self.DashDepatmentsCount_label.setObjectName("DashDepatmentsCount_label")
        self.gridLayout_10.addWidget(self.splitter_5, 1, 3, 1, 1)
        self.splitter_3 = QtWidgets.QSplitter(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_3.sizePolicy().hasHeightForWidth())
        self.splitter_3.setSizePolicy(sizePolicy)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.label_31 = QtWidgets.QLabel(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setObjectName("label_31")
        self.DashDevicesCount_label = QtWidgets.QLabel(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DashDevicesCount_label.sizePolicy().hasHeightForWidth())
        self.DashDevicesCount_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.DashDevicesCount_label.setFont(font)
        self.DashDevicesCount_label.setObjectName("DashDevicesCount_label")
        self.gridLayout_10.addWidget(self.splitter_3, 1, 2, 1, 1)
        self.splitter_4 = QtWidgets.QSplitter(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_4.sizePolicy().hasHeightForWidth())
        self.splitter_4.setSizePolicy(sizePolicy)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.label_33 = QtWidgets.QLabel(self.splitter_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_33.sizePolicy().hasHeightForWidth())
        self.label_33.setSizePolicy(sizePolicy)
        self.label_33.setObjectName("label_33")
        self.DashFormsCount_label = QtWidgets.QLabel(self.splitter_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DashFormsCount_label.sizePolicy().hasHeightForWidth())
        self.DashFormsCount_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.DashFormsCount_label.setFont(font)
        self.DashFormsCount_label.setObjectName("DashFormsCount_label")
        self.gridLayout_10.addWidget(self.splitter_4, 1, 4, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label_25 = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setObjectName("label_25")
        self.DashToDoCount_label = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DashToDoCount_label.sizePolicy().hasHeightForWidth())
        self.DashToDoCount_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.DashToDoCount_label.setFont(font)
        self.DashToDoCount_label.setObjectName("DashToDoCount_label")
        self.gridLayout_10.addWidget(self.splitter, 1, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_7.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Resources/images/paste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon)
        self.pushButton_7.setIconSize(QtCore.QSize(50, 100))
        self.pushButton_7.setFlat(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_10.addWidget(self.pushButton_7, 2, 4, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Resources/images/black-placeholder-variant.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon1)
        self.pushButton_8.setIconSize(QtCore.QSize(50, 100))
        self.pushButton_8.setFlat(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_10.addWidget(self.pushButton_8, 2, 3, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Resources/images/monitor-tool-symbol.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon2)
        self.pushButton_6.setIconSize(QtCore.QSize(50, 100))
        self.pushButton_6.setFlat(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_10.addWidget(self.pushButton_6, 2, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Resources/images/check.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setIconSize(QtCore.QSize(50, 100))
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_10.addWidget(self.pushButton_4, 2, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Resources/images/list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon4)
        self.pushButton_3.setIconSize(QtCore.QSize(50, 100))
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_10.addWidget(self.pushButton_3, 2, 0, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendarWidget.sizePolicy().hasHeightForWidth())
        self.calendarWidget.setSizePolicy(sizePolicy)
        self.calendarWidget.setMinimumSize(QtCore.QSize(750, 300))
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout_8.addWidget(self.calendarWidget, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_10.addLayout(self.gridLayout_8, 3, 0, 1, 5)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Resources/images/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon5, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.ToDo_table = QtWidgets.QTableWidget(self.tab)
        self.ToDo_table.setRowCount(10)
        self.ToDo_table.setObjectName("ToDo_table")
        self.ToDo_table.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.ToDo_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ToDo_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ToDo_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ToDo_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ToDo_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ToDo_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ToDo_table.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ToDo_table.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ToDo_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ToDo_table.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ToDo_table.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ToDo_table.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ToDo_table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ToDo_table.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ToDo_table.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ToDo_table.setItem(2, 3, item)
        self.ToDo_table.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_4.addWidget(self.ToDo_table, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.Export_button = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Export_button.sizePolicy().hasHeightForWidth())
        self.Export_button.setSizePolicy(sizePolicy)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Resources/images/export.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Export_button.setIcon(icon6)
        self.Export_button.setObjectName("Export_button")
        self.gridLayout_5.addWidget(self.Export_button, 0, 1, 1, 1)
        self.Date_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.Date_comboBox.setObjectName("Date_comboBox")
        self.Date_comboBox.addItem("")
        self.Date_comboBox.addItem("")
        self.Date_comboBox.addItem("")
        self.gridLayout_5.addWidget(self.Date_comboBox, 0, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Resources/images/document-rounded-square-interface-symbol-with-text-lines.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon7)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_5.addWidget(self.pushButton_5, 0, 2, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, icon4, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_6.addWidget(self.checkBox, 0, 2, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_2, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Resources/images/calender.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon8)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_6.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.line_10 = QtWidgets.QFrame(self.tab_8)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout.addWidget(self.line_10)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.checkBox_12 = QtWidgets.QCheckBox(self.tab_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_12.sizePolicy().hasHeightForWidth())
        self.checkBox_12.setSizePolicy(sizePolicy)
        self.checkBox_12.setObjectName("checkBox_12")
        self.gridLayout_7.addWidget(self.checkBox_12, 14, 2, 1, 1)
        self.checkBox_11 = QtWidgets.QCheckBox(self.tab_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_11.sizePolicy().hasHeightForWidth())
        self.checkBox_11.setSizePolicy(sizePolicy)
        self.checkBox_11.setObjectName("checkBox_11")
        self.gridLayout_7.addWidget(self.checkBox_11, 12, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_8)
        self.label_2.setObjectName("label_2")
        self.gridLayout_7.addWidget(self.label_2, 0, 0, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.tab_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_3.sizePolicy().hasHeightForWidth())
        self.checkBox_3.setSizePolicy(sizePolicy)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_7.addWidget(self.checkBox_3, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_8)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 2, 0, 1, 1)
        self.checkBox_22 = QtWidgets.QCheckBox(self.tab_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_22.sizePolicy().hasHeightForWidth())
        self.checkBox_22.setSizePolicy(sizePolicy)
        self.checkBox_22.setObjectName("checkBox_22")
        self.gridLayout_7.addWidget(self.checkBox_22, 18, 2, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.tab_8)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout_7.addWidget(self.line_9, 17, 0, 1, 1)
        self.checkBox_21 = QtWidgets.QCheckBox(self.tab_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_21.sizePolicy().hasHeightForWidth())
        self.checkBox_21.setSizePolicy(sizePolicy)
        self.checkBox_21.setObjectName("checkBox_21")
        self.gridLayout_7.addWidget(self.checkBox_21, 16, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_8)
        self.label_11.setObjectName("label_11")
        self.gridLayout_7.addWidget(self.label_11, 12, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_8)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 8, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_8)
        self.label_12.setObjectName("label_12")
        self.gridLayout_7.addWidget(self.label_12, 14, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_8)
        self.label_14.setObjectName("label_14")
        self.gridLayout_7.addWidget(self.label_14, 18, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.tab_8)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_7.addWidget(self.line_2, 3, 0, 1, 1)
        self.checkBox_8 = QtWidgets.QCheckBox(self.tab_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_8.sizePolicy().hasHeightForWidth())
        self.checkBox_8.setSizePolicy(sizePolicy)
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout_7.addWidget(self.checkBox_8, 6, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_8)
        self.label_3.setObjectName("label_3")
        self.gridLayout_7.addWidget(self.label_3, 4, 0, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.tab_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_4.sizePolicy().hasHeightForWidth())
        self.checkBox_4.setSizePolicy(sizePolicy)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_7.addWidget(self.checkBox_4, 4, 2, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.tab_8)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_7.addWidget(self.line_3, 5, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_8)
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 16, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.tab_8)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_7.addWidget(self.line_5, 9, 0, 1, 1)
        self.checkBox_10 = QtWidgets.QCheckBox(self.tab_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_10.sizePolicy().hasHeightForWidth())
        self.checkBox_10.setSizePolicy(sizePolicy)
        self.checkBox_10.setObjectName("checkBox_10")
        self.gridLayout_7.addWidget(self.checkBox_10, 10, 2, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_2.sizePolicy().hasHeightForWidth())
        self.checkBox_2.setSizePolicy(sizePolicy)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_7.addWidget(self.checkBox_2, 0, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.tab_8)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_7.addWidget(self.line, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_8)
        self.label_10.setObjectName("label_10")
        self.gridLayout_7.addWidget(self.label_10, 10, 0, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.tab_8)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_7.addWidget(self.line_6, 11, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.tab_8)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_7.addWidget(self.line_4, 7, 0, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.tab_8)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_7.addWidget(self.line_7, 13, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_8)
        self.label_4.setObjectName("label_4")
        self.gridLayout_7.addWidget(self.label_4, 6, 0, 1, 1)
        self.checkBox_9 = QtWidgets.QCheckBox(self.tab_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_9.sizePolicy().hasHeightForWidth())
        self.checkBox_9.setSizePolicy(sizePolicy)
        self.checkBox_9.setObjectName("checkBox_9")
        self.gridLayout_7.addWidget(self.checkBox_9, 8, 2, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.tab_8)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_7.addWidget(self.line_8, 15, 0, 1, 1)
        self.SubmitAnswers_button = QtWidgets.QPushButton(self.tab_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubmitAnswers_button.sizePolicy().hasHeightForWidth())
        self.SubmitAnswers_button.setSizePolicy(sizePolicy)
        self.SubmitAnswers_button.setObjectName("SubmitAnswers_button")
        self.gridLayout_7.addWidget(self.SubmitAnswers_button, 19, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_7)
        self.line_11 = QtWidgets.QFrame(self.tab_8)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout.addWidget(self.line_11)
        self.tabWidget.addTab(self.tab_8, icon3, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("Resources/images/follow-up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page, icon9, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 1013, 618))
        self.page_2.setObjectName("page_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.page_2)
        self.tabWidget_2.setIconSize(QtCore.QSize(100, 50))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.DepartmentSelection_combo = QtWidgets.QComboBox(self.tab_6)
        self.DepartmentSelection_combo.setObjectName("DepartmentSelection_combo")
        self.DepartmentSelection_combo.addItem("")
        self.DepartmentSelection_combo.addItem("")
        self.DepartmentSelection_combo.addItem("")
        self.DepartmentSelection_combo.addItem("")
        self.verticalLayout_6.addWidget(self.DepartmentSelection_combo)
        self.Devices_table = QtWidgets.QTableWidget(self.tab_6)
        self.Devices_table.setRowCount(10)
        self.Devices_table.setObjectName("Devices_table")
        self.Devices_table.setColumnCount(13)
        item = QtWidgets.QTableWidgetItem()
        self.Devices_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Devices_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Devices_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Devices_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Devices_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Devices_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Devices_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.Devices_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.Devices_table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.Devices_table.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.Devices_table.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.Devices_table.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.Devices_table.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.Devices_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Devices_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Devices_table.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Devices_table.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Devices_table.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Devices_table.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Devices_table.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.Devices_table.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.Devices_table.setItem(0, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.Devices_table.setItem(0, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.Devices_table.setItem(0, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.Devices_table.setItem(0, 12, item)
        self.verticalLayout_6.addWidget(self.Devices_table)
        self.tabWidget_2.addTab(self.tab_6, icon2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.DepartmentSelection_combo_2 = QtWidgets.QComboBox(self.tab_4)
        self.DepartmentSelection_combo_2.setObjectName("DepartmentSelection_combo_2")
        self.DepartmentSelection_combo_2.addItem("")
        self.DepartmentSelection_combo_2.addItem("")
        self.DepartmentSelection_combo_2.addItem("")
        self.DepartmentSelection_combo_2.addItem("")
        self.verticalLayout_2.addWidget(self.DepartmentSelection_combo_2)
        self.Department_table = QtWidgets.QTableWidget(self.tab_4)
        self.Department_table.setRowCount(3)
        self.Department_table.setObjectName("Department_table")
        self.Department_table.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.Department_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Department_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Department_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Department_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Department_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Department_table.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Department_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Department_table.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Department_table.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Department_table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Department_table.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Department_table.setItem(2, 2, item)
        self.Department_table.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.Department_table)
        self.tabWidget_2.addTab(self.tab_4, icon1, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_7)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.DepartmentSelection_combo_3 = QtWidgets.QComboBox(self.tab_7)
        self.DepartmentSelection_combo_3.setObjectName("DepartmentSelection_combo_3")
        self.DepartmentSelection_combo_3.addItem("")
        self.DepartmentSelection_combo_3.addItem("")
        self.DepartmentSelection_combo_3.addItem("")
        self.DepartmentSelection_combo_3.addItem("")
        self.verticalLayout_4.addWidget(self.DepartmentSelection_combo_3)
        self.Forms_table = QtWidgets.QTableWidget(self.tab_7)
        self.Forms_table.setRowCount(10)
        self.Forms_table.setObjectName("Forms_table")
        self.Forms_table.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.Forms_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Forms_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Forms_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Forms_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Forms_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Forms_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Forms_table.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Forms_table.setItem(0, 3, item)
        self.Forms_table.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_4.addWidget(self.Forms_table)
        self.tabWidget_2.addTab(self.tab_7, icon3, "")
        self.gridLayout_3.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("Resources/images/request.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page_2, icon10, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 1013, 618))
        self.page_3.setObjectName("page_3")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.groupBox_5 = QtWidgets.QGroupBox(self.page_3)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.CreateForm_button = QtWidgets.QPushButton(self.groupBox_5)
        self.CreateForm_button.setMinimumSize(QtCore.QSize(250, 250))
        self.CreateForm_button.setIcon(icon3)
        self.CreateForm_button.setIconSize(QtCore.QSize(150, 150))
        self.CreateForm_button.setFlat(True)
        self.CreateForm_button.setObjectName("CreateForm_button")
        self.horizontalLayout_3.addWidget(self.CreateForm_button)
        self.gridLayout_18.addWidget(self.groupBox_5, 0, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.page_3)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.AddDevice_button = QtWidgets.QPushButton(self.groupBox_4)
        self.AddDevice_button.setMinimumSize(QtCore.QSize(250, 250))
        self.AddDevice_button.setIcon(icon2)
        self.AddDevice_button.setIconSize(QtCore.QSize(150, 150))
        self.AddDevice_button.setFlat(True)
        self.AddDevice_button.setObjectName("AddDevice_button")
        self.horizontalLayout_2.addWidget(self.AddDevice_button)
        self.gridLayout_18.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.page_3)
        self.groupBox_11.setObjectName("groupBox_11")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_11)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ManageTasks_button = QtWidgets.QPushButton(self.groupBox_11)
        self.ManageTasks_button.setMinimumSize(QtCore.QSize(250, 250))
        self.ManageTasks_button.setIcon(icon4)
        self.ManageTasks_button.setIconSize(QtCore.QSize(150, 150))
        self.ManageTasks_button.setFlat(True)
        self.ManageTasks_button.setObjectName("ManageTasks_button")
        self.horizontalLayout_4.addWidget(self.ManageTasks_button)
        self.gridLayout_18.addWidget(self.groupBox_11, 0, 2, 1, 1)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("Resources/images/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page_3, icon11, "")
        self.gridLayout.addWidget(self.toolBox, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1033, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuWindow = QtWidgets.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionCMMS = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("Resources/images/app.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCMMS.setIcon(icon12)
        self.actionCMMS.setObjectName("actionCMMS")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("Resources/images/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon13)
        self.actionOpen.setObjectName("actionOpen")
        self.actionRequests = QtWidgets.QAction(MainWindow)
        self.actionRequests.setIcon(icon10)
        self.actionRequests.setObjectName("actionRequests")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("Resources/images/cross-gross-symbol.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon14)
        self.actionExit.setObjectName("actionExit")
        self.actionTo_Do = QtWidgets.QAction(MainWindow)
        self.actionTo_Do.setIcon(icon4)
        self.actionTo_Do.setObjectName("actionTo_Do")
        self.actionHome = QtWidgets.QAction(MainWindow)
        self.actionHome.setIcon(icon5)
        self.actionHome.setObjectName("actionHome")
        self.actionDaily_Inspection = QtWidgets.QAction(MainWindow)
        self.actionDaily_Inspection.setIcon(icon3)
        self.actionDaily_Inspection.setObjectName("actionDaily_Inspection")
        self.actionFollow_Up = QtWidgets.QAction(MainWindow)
        self.actionFollow_Up.setIcon(icon9)
        self.actionFollow_Up.setObjectName("actionFollow_Up")
        self.actionInformation = QtWidgets.QAction(MainWindow)
        self.actionInformation.setIcon(icon10)
        self.actionInformation.setObjectName("actionInformation")
        self.actionAdd_Device = QtWidgets.QAction(MainWindow)
        self.actionAdd_Device.setIcon(icon2)
        self.actionAdd_Device.setObjectName("actionAdd_Device")
        self.actionTools = QtWidgets.QAction(MainWindow)
        self.actionTools.setIcon(icon11)
        self.actionTools.setObjectName("actionTools")
        self.actionCreate_Form = QtWidgets.QAction(MainWindow)
        self.actionCreate_Form.setIcon(icon3)
        self.actionCreate_Form.setObjectName("actionCreate_Form")
        self.actionManage_Tasks = QtWidgets.QAction(MainWindow)
        self.actionManage_Tasks.setIcon(icon4)
        self.actionManage_Tasks.setObjectName("actionManage_Tasks")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionCMMS)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionFollow_Up)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionHome)
        self.toolBar.addAction(self.actionTo_Do)
        self.toolBar.addAction(self.actionDaily_Inspection)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionInformation)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionTools)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionAdd_Device)
        self.toolBar.addAction(self.actionCreate_Form)
        self.toolBar.addAction(self.actionManage_Tasks)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCMMS)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExit)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(2)
        self.Date_comboBox.setCurrentIndex(2)
        self.comboBox_2.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_29.setText(_translate("MainWindow", "Tasks:"))
        self.DashTasksCount_label.setText(_translate("MainWindow", "2"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Search"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Search for To Do, Tasks, Devices,..etc"))
        self.label_35.setText(_translate("MainWindow", "Departments:"))
        self.DashDepatmentsCount_label.setText(_translate("MainWindow", "0"))
        self.label_31.setText(_translate("MainWindow", "Devices:"))
        self.DashDevicesCount_label.setText(_translate("MainWindow", "0"))
        self.label_33.setText(_translate("MainWindow", "Forms:"))
        self.DashFormsCount_label.setText(_translate("MainWindow", "0"))
        self.label_25.setText(_translate("MainWindow", "To Do:"))
        self.DashToDoCount_label.setText(_translate("MainWindow", "3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Dashboard"))
        self.ToDo_table.setSortingEnabled(True)
        item = self.ToDo_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Task"))
        item = self.ToDo_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Date"))
        item = self.ToDo_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Status"))
        item = self.ToDo_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Comment"))
        __sortingEnabled = self.ToDo_table.isSortingEnabled()
        self.ToDo_table.setSortingEnabled(False)
        item = self.ToDo_table.item(0, 0)
        item.setText(_translate("MainWindow", "Task X"))
        item = self.ToDo_table.item(0, 1)
        item.setText(_translate("MainWindow", "13/5/2020"))
        item = self.ToDo_table.item(0, 2)
        item.setText(_translate("MainWindow", "In-Progress"))
        item = self.ToDo_table.item(0, 3)
        item.setText(_translate("MainWindow", "This is test item for evaluation purpose only!"))
        item = self.ToDo_table.item(1, 0)
        item.setText(_translate("MainWindow", "Task Y"))
        item = self.ToDo_table.item(1, 1)
        item.setText(_translate("MainWindow", "13/5/2020"))
        item = self.ToDo_table.item(1, 2)
        item.setText(_translate("MainWindow", "Done"))
        item = self.ToDo_table.item(1, 3)
        item.setText(_translate("MainWindow", "This is test item for evaluation purpose only!"))
        item = self.ToDo_table.item(2, 0)
        item.setText(_translate("MainWindow", "Review"))
        item = self.ToDo_table.item(2, 1)
        item.setText(_translate("MainWindow", "13/5/2020"))
        item = self.ToDo_table.item(2, 2)
        item.setText(_translate("MainWindow", "On-Hold"))
        item = self.ToDo_table.item(2, 3)
        item.setText(_translate("MainWindow", "This is test item for evaluation purpose only!"))
        self.ToDo_table.setSortingEnabled(__sortingEnabled)
        self.groupBox.setTitle(_translate("MainWindow", "View:"))
        self.Export_button.setText(_translate("MainWindow", "Export..."))
        self.Date_comboBox.setItemText(0, _translate("MainWindow", "7 Days"))
        self.Date_comboBox.setItemText(1, _translate("MainWindow", "3 Days"))
        self.Date_comboBox.setItemText(2, _translate("MainWindow", "Today"))
        self.pushButton_5.setText(_translate("MainWindow", "Print..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "To Do"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Task:"))
        self.checkBox.setText(_translate("MainWindow", "Mark as Done"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Task X"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Task Y"))
        self.pushButton_2.setText(_translate("MainWindow", "13/5/2020"))
        self.checkBox_12.setText(_translate("MainWindow", "Done"))
        self.checkBox_11.setText(_translate("MainWindow", "Done"))
        self.label_2.setText(_translate("MainWindow", "Fix Lights"))
        self.checkBox_3.setText(_translate("MainWindow", "Done"))
        self.label.setText(_translate("MainWindow", "Fix Beds"))
        self.checkBox_22.setText(_translate("MainWindow", "Done"))
        self.checkBox_21.setText(_translate("MainWindow", "Done"))
        self.label_11.setText(_translate("MainWindow", "Hhhh"))
        self.label_9.setText(_translate("MainWindow", "Clean Windows"))
        self.label_12.setText(_translate("MainWindow", "HHHH"))
        self.label_14.setText(_translate("MainWindow", "HhHh"))
        self.checkBox_8.setText(_translate("MainWindow", "Done"))
        self.label_3.setText(_translate("MainWindow", "Fix MRI"))
        self.checkBox_4.setText(_translate("MainWindow", "Done"))
        self.label_13.setText(_translate("MainWindow", "hhhh"))
        self.checkBox_10.setText(_translate("MainWindow", "Done"))
        self.checkBox_2.setText(_translate("MainWindow", "Done"))
        self.label_10.setText(_translate("MainWindow", "Install Word 2007"))
        self.label_4.setText(_translate("MainWindow", "Fix X-Ray"))
        self.checkBox_9.setText(_translate("MainWindow", "Done"))
        self.SubmitAnswers_button.setText(_translate("MainWindow", "Submit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "Inspection"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Follow-Up"))
        self.DepartmentSelection_combo.setItemText(0, _translate("MainWindow", "All Departments"))
        self.DepartmentSelection_combo.setItemText(1, _translate("MainWindow", "Operating Room"))
        self.DepartmentSelection_combo.setItemText(2, _translate("MainWindow", "ICU"))
        self.DepartmentSelection_combo.setItemText(3, _translate("MainWindow", "Radiology"))
        item = self.Devices_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.Devices_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Device"))
        item = self.Devices_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Type"))
        item = self.Devices_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Model"))
        item = self.Devices_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Serial Number"))
        item = self.Devices_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Manufacturer"))
        item = self.Devices_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Installation Date"))
        item = self.Devices_table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "PPM Period"))
        item = self.Devices_table.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Family"))
        item = self.Devices_table.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Vendor"))
        item = self.Devices_table.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Warranty"))
        item = self.Devices_table.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "PPM ID"))
        item = self.Devices_table.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Department ID"))
        __sortingEnabled = self.Devices_table.isSortingEnabled()
        self.Devices_table.setSortingEnabled(False)
        item = self.Devices_table.item(0, 0)
        item.setText(_translate("MainWindow", "001"))
        item = self.Devices_table.item(0, 1)
        item.setText(_translate("MainWindow", "MRI"))
        item = self.Devices_table.item(0, 2)
        item.setText(_translate("MainWindow", "TEST"))
        item = self.Devices_table.item(0, 3)
        item.setText(_translate("MainWindow", "TEST"))
        item = self.Devices_table.item(0, 4)
        item.setText(_translate("MainWindow", "32RGS432FSA"))
        item = self.Devices_table.item(0, 5)
        item.setText(_translate("MainWindow", "TEST"))
        item = self.Devices_table.item(0, 6)
        item.setText(_translate("MainWindow", "13/5/2020"))
        item = self.Devices_table.item(0, 7)
        item.setText(_translate("MainWindow", "001"))
        item = self.Devices_table.item(0, 8)
        item.setText(_translate("MainWindow", "TEST"))
        item = self.Devices_table.item(0, 9)
        item.setText(_translate("MainWindow", "TEST"))
        item = self.Devices_table.item(0, 10)
        item.setText(_translate("MainWindow", "1 Year"))
        item = self.Devices_table.item(0, 12)
        item.setText(_translate("MainWindow", "002"))
        self.Devices_table.setSortingEnabled(__sortingEnabled)
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Devices"))
        self.DepartmentSelection_combo_2.setItemText(0, _translate("MainWindow", "All Departments"))
        self.DepartmentSelection_combo_2.setItemText(1, _translate("MainWindow", "Operating Room"))
        self.DepartmentSelection_combo_2.setItemText(2, _translate("MainWindow", "ICU"))
        self.DepartmentSelection_combo_2.setItemText(3, _translate("MainWindow", "Radiology"))
        item = self.Department_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.Department_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Department"))
        item = self.Department_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Location"))
        __sortingEnabled = self.Department_table.isSortingEnabled()
        self.Department_table.setSortingEnabled(False)
        item = self.Department_table.item(0, 0)
        item.setText(_translate("MainWindow", "001"))
        item = self.Department_table.item(0, 1)
        item.setText(_translate("MainWindow", "Operating Room"))
        item = self.Department_table.item(0, 2)
        item.setText(_translate("MainWindow", "Basement"))
        item = self.Department_table.item(1, 0)
        item.setText(_translate("MainWindow", "002"))
        item = self.Department_table.item(1, 1)
        item.setText(_translate("MainWindow", "Radiology"))
        item = self.Department_table.item(1, 2)
        item.setText(_translate("MainWindow", "Basement"))
        item = self.Department_table.item(2, 0)
        item.setText(_translate("MainWindow", "003"))
        item = self.Department_table.item(2, 1)
        item.setText(_translate("MainWindow", "Intensive Care Unit (ICU)"))
        item = self.Department_table.item(2, 2)
        item.setText(_translate("MainWindow", "Basement"))
        self.Department_table.setSortingEnabled(__sortingEnabled)
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Departments"))
        self.DepartmentSelection_combo_3.setItemText(0, _translate("MainWindow", "All Departments"))
        self.DepartmentSelection_combo_3.setItemText(1, _translate("MainWindow", "Operating Room"))
        self.DepartmentSelection_combo_3.setItemText(2, _translate("MainWindow", "ICU"))
        self.DepartmentSelection_combo_3.setItemText(3, _translate("MainWindow", "Radiology"))
        item = self.Forms_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.Forms_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Type"))
        item = self.Forms_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Family"))
        item = self.Forms_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Text"))
        __sortingEnabled = self.Forms_table.isSortingEnabled()
        self.Forms_table.setSortingEnabled(False)
        item = self.Forms_table.item(0, 0)
        item.setText(_translate("MainWindow", "001"))
        item = self.Forms_table.item(0, 1)
        item.setText(_translate("MainWindow", "Question"))
        item = self.Forms_table.item(0, 2)
        item.setText(_translate("MainWindow", "MRI"))
        item = self.Forms_table.item(0, 3)
        item.setText(_translate("MainWindow", "Q1$Q2$Q3$$FDFASFAASFASFAFASFAGF$$DAFAFFAFASGASGSAGA"))
        self.Forms_table.setSortingEnabled(__sortingEnabled)
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainWindow", "Forms"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Information"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Create Form"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Add Device"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Manage Tasks"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "Tools"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuWindow.setTitle(_translate("MainWindow", "Window"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionCMMS.setText(_translate("MainWindow", "About CMMS"))
        self.actionCMMS.setShortcut(_translate("MainWindow", "?"))
        self.actionOpen.setText(_translate("MainWindow", "Exit"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionRequests.setText(_translate("MainWindow", "Requests"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.actionTo_Do.setText(_translate("MainWindow", "To Do"))
        self.actionHome.setText(_translate("MainWindow", "Home"))
        self.actionDaily_Inspection.setText(_translate("MainWindow", "Inspection"))
        self.actionFollow_Up.setText(_translate("MainWindow", "Follow-Up"))
        self.actionInformation.setText(_translate("MainWindow", "Information"))
        self.actionAdd_Device.setText(_translate("MainWindow", "Add Device"))
        self.actionTools.setText(_translate("MainWindow", "Tools"))
        self.actionCreate_Form.setText(_translate("MainWindow", "Create Form"))
        self.actionManage_Tasks.setText(_translate("MainWindow", "Manage Tasks"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
